DjangoWebProject/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from app.models import CustomUser, GTSIL_Results_Distribution
from rest_framework import routers, serializers, viewsets
from django.utils.translation import ugettext_lazy as _
import django_filters
from rest_framework import filters
from rest_framework import generics


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = CustomUser
        fields = ('url', 'username', 'is_staff', 'status_confirmed')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

"""
class UserSerializer(serializers.Serializer):
    email = serializers.EmailField()
    username = serializers.CharField(max_length=100)

class CommentSerializer(serializers.Serializer):
    user = UserSerializer()
    content = serializers.CharField(max_length=200)
    created = serializers.DateTimeField()
"""

class GroupSerializer(serializers.Serializer):
    name = serializers.CharField(max_length = 100)

class LectureSerializer(serializers.Serializer):
    lecture_start_time = serializers.DateTimeField()

class SubjectSerializer(serializers.Serializer):
    full_name = serializers.CharField(max_length = 100)
    subject_id = serializers.CharField(max_length=10)
class InstructorSerializer(serializers.Serializer):
    cist_id = serializers.CharField(max_length=5)
    last_name = serializers.CharField(max_length = 50)
    first_name = serializers.CharField(max_length = 50)
    middle_name = serializers.CharField(max_length = 50)
class CriteriaSerializer(serializers.Serializer):
    criteria_name = serializers.CharField(max_length=100)

class GTSILResultDistributionSerializer(serializers.HyperlinkedModelSerializer):
    lecture = LectureSerializer()
    group = GroupSerializer()
    subject = SubjectSerializer()
    instructor = InstructorSerializer()
    criteria = CriteriaSerializer()

    class Meta:
        model = GTSIL_Results_Distribution

class GTSILResultDistributionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = GTSIL_Results_Distribution.objects.all()
    serializer_class = GTSILResultDistributionSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('instructor', 'criteria','group', 'subject', 'lecture__gtsi__activity_type')
"""
class GTSILResultDistributionQueryViewSet(viewsets.ModelViewSet):
    queryset = GTSIL_Results_Distribution.objects.all()
    serializer_class = GTSILResultDistributionSerializer
    def get_querysety(self):
"""

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
#router.register(r'users', UserViewSet)
router.register(r'distributions', GTSILResultDistributionViewSet)
#router.register(r'distributions/subject=(?P<subject_id>.+)/(?P<instructor_id>.+)/(?P<activity_id>.+)$', GTSILResultDistributionQueryViewSet)

# Uncomment the next lines to enable the admin:
admin.autodiscover()

urlpatterns = [
    url(r'^', include('app.urls', namespace="main")),
    url(r'^', include('news.urls', namespace="news")),
    url(r'^',include('blog.urls', namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^apiz/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

app/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from django.views.generic import TemplateView
from app.views import (Index, Register, UserLogin, 
    RegisterStudent, RegisterInstructor, 
    AboutFeedbacker, AboutUs, 
    My, UserLogout, RegisterConfirm,
    ConfirmStatus, AttachGroup,
    EvaluateLecture, EvaluateSubject,
    FindProfile, AttachProfile,
    LectureResults, LectureResultsGraphData, SubjectResults,
    SubjectResultsGraphData, GroupsAndCriteria, Faq, ContactAdmin,
    TakeSurvey, ShowGroupInfo, MyProfile, Tutorials, TestResults,
    RefreshSchedule, StudentRatingView, OpenStudentRating, EditStudentRating,
    DeleteStudentRating, ShowComplaints)
from app.api import GTSILFeedback, Subjects
from app.views import email_exists, username_exists
from django.utils.translation import ugettext_lazy as _
from rest_framework import routers
from app import api
# Uncomment the next lines to enable the admin:
admin.autodiscover()
router = routers.DefaultRouter()
router.register(r'users', api.UserViewSet)
router.register(r'groups', api.GroupViewSet)

urlpatterns = patterns('',
    # Examples:
    url(r'^$', Index.as_view(), name = 'index'),    
    url(r'^login/$', UserLogin.as_view(), name = 'login'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls'), name = 'admin_doc'),

    # Uncomment the next line to enable the admin:
    url(r'^register/$', Register.as_view(), name = 'register'),
    url(r'^register/', include(patterns('',
        url(r'^student/$', RegisterStudent.as_view(), name = 'register_student'),
        url(r'^instructor/$', RegisterInstructor.as_view(), name = 'register_instructor'),
    ))),
    # url(r'^register_student/$', RegisterStudent.as_view(), name = 'register_student'),
    # url(r'^register_instructor/$', RegisterInstructor.as_view(), name = 'register_instructor'),
    url(r'^confirm_status/$', ConfirmStatus.as_view(), name = 'confirm_status'),
    url(r'^attach_group/$', AttachGroup.as_view(), name = 'attach_group'),
    url(_(r'^my/$'), My.as_view(), name = 'my'),
    url(r'^logout/$', UserLogout.as_view(), name = 'logout'),
    url(r'^about_us/$', AboutUs.as_view(), name = 'about_us'),
    url(r'^contact_admin/', ContactAdmin.as_view(), name = 'contact_admin'),
    url(r'^faq/$', Faq.as_view(), name='faq'),
    url(r'^about_feedbacker/$', AboutFeedbacker.as_view(), name = 'about_feedbacker'),            
    url(r'^admin/', include(admin.site.urls), name = 'admin'),
    url(r'^confirm/(?P<activation_key>\w+)/', RegisterConfirm.as_view(), name = 'confirm'),
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'registration/password_reset_form.html', 'post_reset_redirect' : '/user/password/reset/done/'}, name="password_reset"),
    (r'^user/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm', 
        {'post_reset_redirect' : '/user/password/done/'}),
    (r'^user/password/done/$',
        'django.contrib.auth.views.password_reset_complete'),
    url(r'^subjects/(?P<gtsi_id>\d+)/$', EvaluateSubject.as_view(), name='subject'),
    url(r'^subjects/(?P<gtsi_id>\d+)/vote/$', EvaluateSubject.as_view(), name='vote_subject'),
    url(r'^lectures/(?P<gtsil_id>\d+)/$', EvaluateLecture.as_view(), name='lecture'),
    url(r'^lectures/vote/(?P<gtsil_id>\d+)/$', EvaluateLecture.as_view(), name='vote_lecture'),
    url(r'^username_exists/(?P<username>([A-Z]|[a-z]|[0-9]|\.|_|\-){3,30})$', username_exists),
    url(r'^email_exists/(?P<email>([A-Z]|[a-z]|[0-9]|\@|\.|_|\-){3,30})$', email_exists),
    url(r'^find_profile/$', FindProfile.as_view(), name = 'find_profile'),
    url(r'^attach_profile/(?P<instructor_id>\d+)/$', AttachProfile.as_view(), name = 'attach_profile'),
    url(r'^results/(?P<gtsil_id>\d+)/$', LectureResults.as_view(), name='lecture_results'),
    url(r'^subject_results/(?P<subject_id>\d+)/$', SubjectResults.as_view(), name='subject_results'),
    url(r'^graphdata/$', LectureResultsGraphData.as_view(), name='graphdata'),
    url(r'^subjgraphdata/$', SubjectResultsGraphData.as_view(), name = 'subjgraphdata'),
    url(r'^getgroupscrit/$', GroupsAndCriteria.as_view(), name='getgroupscrit'),
    url(r'^api/v1/lectures/(?P<gtsil_id>\d+)/$', GTSILFeedback.as_view(), name='gtsil_feedback_api'),
    url(r'^api/v1/subjects/$', Subjects.as_view(), name='subjects_api'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^surveys/(?P<survey_id>\w+-\w+-\w+-\w+-\w+)/$', TakeSurvey.as_view(), name = 'survey'),
    url(r'^group/(?P<group_id>\w+)/$', ShowGroupInfo.as_view(), name = 'group_info'),
    url(r'^my/profile/$', MyProfile.as_view(), name = 'my_profile'),
    url(r'^tutorials/$', Tutorials.as_view(), name = 'tutorials'),
    url(r'^survey_results/(?P<survey_id>\w+-\w+-\w+-\w+-\w+)/(?P<group_id>\d+)/$', TestResults.as_view(), name = 'survey_results'),
    url(r'^refresh_schedule/$', RefreshSchedule.as_view(), name = 'refresh_schedule'),
    url(r'^student_rating/$', StudentRatingView.as_view(), name='student_rating'),
    url(r'^open_student_rating/$', OpenStudentRating.as_view(), name='open_student_rating'),
    url(r'^edit_student_rating/(?P<rating_id>\d+)/$', EditStudentRating.as_view(), name='edit_student_rating'),
    url(r'^delete_student_rating/(?P<rating_id>\d+)/$', DeleteStudentRating.as_view(), name='delete_student_rating'),
    url(r'^show_complaints/$', ShowComplaints.as_view(), name='show_complaints'),
    # url(r'^confirm_status_page/$', ConfirmStatusPage.as_view(), name="confirm_status_page"),
)

blog/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from django.views.generic import TemplateView
from blog.views import (Blog, CreateBlogView, BlogPostView, UpdateBlogPostView,
    DeleteBlogPostView, UpdateCommentView, DeleteCommentView)
from django.utils.translation import ugettext_lazy as _

# Uncomment the next lines to enable the admin:
admin.autodiscover()


urlpatterns = patterns('',
	url(r'^blog/$', Blog.as_view(), name='blog',),
    url(r'^new$', CreateBlogView.as_view(), name='blog-new',),
    url(r'^(?P<pk>\d+)/$', BlogPostView.as_view(), name='blogpost-view',),
    url(r'^edit/(?P<pk>\d+)/$', UpdateBlogPostView.as_view(), name='blogpost-edit',),
    url(r'^(?P<blogpost_id>\d+)/edit_comment/(?P<pk>\d+)/$', UpdateCommentView.as_view(), name='comment-edit',),
    url(r'^delete/(?P<pk>\d+)/$', DeleteBlogPostView.as_view(), name='blogpost-delete',),
    url(r'^(?P<blogpost_id>\d+)/delete-comment/(?P<pk>\d+)/$', DeleteCommentView.as_view(), name='comment-delete',),)

templates/app/about_feedbacker.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>FEEDBACKER</title>        
    </head>

    <body>    
    <a href="/">Main page</a><br />
    <h1>О Feedbacker</h1>
<p>Feedbacker – это система обратной связи для студентов и преподавателей. Мы все хотим, чтобы страна, в которой мы живем, стала частичкой Европы не только на словах, но и на деле. Для этого мы должны постоянно слушать и слышать друг друга. Мы не можем изменить весь мир, но мы можем попробовать изменить пространство вокруг нас. Для этого мы и создали Feedbacker. </p>
<p>
<h2>Если ты студент:</h2><br/>
<p>С помощью Feedbacker ты сможешь лучше узнать своих преподавателей, понять, как учить их предметы: посещать все лекции или углубиться в учебник. Ты сможешь задавать вопросы к консультациям и скачивать выложенные преподавателем слайды. Ну и самое приятное — здесь именно ты ставишь преподавателю оценки. Возможно, не сегодня, не сейчас, но очень скоро в нашей стране, так же, как и в других развитых странах, одним из важнейших критериев хорошего преподавателя будет считаться умение научить и объяснить понятно сложные вещи. А как понять, насколько хорошо это получается у преподавателя? Дать обратную связь!</p>

<h2>Если вы преподаватель:</h2><br/>
<p>Вы сможете в режиме реального времени получать фидбэк от студентов. Сразу же после лекции вы сможете получить ответ на вопрос «Как прошла моя лекция сегодня?». Вы также сможете сами создавать нужные вам опросы, чтобы узнать мнение студентов по тому или иному вопросу. А еще вы сможете оценить нагрузку студентов и посмотреть, сколько времени у них заняли ваши предыдущие задания. И здесь же вы сможете заранее получить вопросы к консультации и понять, какие темы оказались самыми сложными. Мы, студенты, верим, что вы действительно хотите научить нас, и поэтому вам не все равно, что мы думаем.</p>    
    </body>

</html>

templates/app/about_us.html
{% extends "app/base.html" %}
{% load staticfiles %}
		{% block title %}About us{% endblock %}
		{% block url %}
		<link rel = "stylesheet" 	href="{% static "app/css/about.css" %}" />
		{% endblock %}
		{% block content %}
			<div id="about_txt">Немного о составе Carrotz</div>
			<div class="card transition">
  				<h2 class="transition">Ana Makarevich</h2>
  				<p>Чиф среди чифоф. Крутой организатор. Человек, повидавший АД. Подняла сервер с бд за неделю, спарсила БД за день</p>
  				<div class="card_circle transition"></div>
			</div>
			<div class="card2 transition">
  				<h2 class="transition">Sophy Vitrishko</h2>
  				<p>Джуниор, который станет одним из лучших сеньоров Украины</p>
  				<div class="card2_circle transition"></div>
			</div>
			<div class="card3 transition">
  				<h2 class="transition">Roman Suvorov</h2>
  				<p>Прекрасный программист, умеющий делать всё качественно, И ТОЖЕ ЖДЕТ 3G В ХАРЬКОВЕ</p>
  				<div class="card3_circle transition"></div>
			</div>
			<div class="card4 transition">
  				<h2 class="transition">Vladislav Dmitriev</h2>
  				<p>ЗАТО ШРИФТ КРАСИВЫЙ! А аватарки я пережал :Р</p>
  				<div class="card4_circle transition"></div>
			</div>
				<button id="but"><a href="/" style="color: #fff">Назад</a></button>
		{% endblock %}

templates/app/blogpost_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Блог разработчиков{% endblock %}

{% block scripts %} 
<script>$('#about_us_li').addClass('active');</script> 
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-2 col-sm-2 col-xs-0"></div>
    <div class="col-lg-8 col-sm-8 col-xs-12">
        <div class="panel-body">
            {% if user.is_superuser %}
            <div class="btn-group">
                <a href="{% url 'main:blog-new' %}"><button class="btn btn-primary" id="submit" title="Новый пост">Новый пост</button></a>
            </div>
            {% endif %}
            <div class="blog">
                {% for post in object_list %}
                <div class="blog-post">
                    <div class="blog-post-header">
                        <div class="blog-post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></div>
                        <div class="blog-post-author">{{ post.author }}</div>
                        <div class="blog-post-date">{{ post.timestamp.date }}</div>
                        {% if user == post.author %}
                        <a href="{% url 'main:blogpost-edit' pk=post.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="{% url 'main:blogpost-delete' pk=post.id %}"><span class="glyphicon glyphicon-remove" style="color:#B80000;"></span></a>
                        {% endif %}
                    </div>
                    {% autoescape off %}
                    <div class="blog-post-body shrinked" id="blog-post-body_{{ forloop.counter }}">{{ post.body }}</div>
                    <script>
                        blog_post_body_current = document.getElementById("blog-post-body_{{ forloop.counter }}");
                        bpost_max_length = 500;
                        new_read_full_button = document.createElement("div");

                        new_read_full_button.className = "blog-post-show-full";
                        new_read_full_button.innerHTML = "<a href='{{ post.get_absolute_url }}'><button class='btn btn-default' title='Перейти к просмотру полной версии поста'>Читать дальше →</button></a>"; 
                        if (blog_post_body_current.innerHTML.length > bpost_max_length)
                        {
                            blog_post_body_current.innerHTML = blog_post_body_current.innerHTML.substr(0, bpost_max_length - 4) + " …";
                            blog_post_body_current.parentNode.insertBefore(new_read_full_button, blog_post_body_current.nextSibling);
                        }
                        blog_post_body_current.classList.add("ready");
                    </script>
                    {% endautoescape %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-lg-2 col-sm-2 col-xs-0"></div>
    <div class="text-center">
        <ul class="pagination">
            {% if object_list.has_previous %}
            <li><a href="?page=1" title="Самое новое"><span>&lt&lt</span></a></li>
            <li><a href="?page={{ object_list.previous_page_number }}" title="Новее">&lt</a></li>
            {% endif %}

            {% for page_num in object_list.paginator.page_range %}
            {% if object_list.number == page_num %}
            <li class="active"><a href="?page={{ page_num }}" onclick="return false;">{{ page_num }}</a></li>
            {% else %}
                {% if page_num < 10 or page_num == object_list.paginator.num_pages %}
                <li><a href="?page={{ page_num }}"> {{ page_num }}</a></li>
                {% else %}
                {% if page_num == 11 %}
                <li><a href="?page={{ page_num }}">...</a></li>
                {% endif %}
                {% endif %}
            {% endif %}
            {% endfor %}
            
            {% if object_list.has_next %}
            <li><a href="?page={{ object_list.next_page_number }}" title="Старее">&gt</a></li>
            <li><a href="?page={{ object_list.paginator.num_pages }}" title="Самое старое"><span>&gt&gt</span></a></li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

templates/app/confirm.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>FEEDBACKER</title>        
    </head>

    <body>    
    <a href="/">Main page</a><br />
    <h1>Все в порядке, ваш аккаунт активирован, можете уже, наконец, войти. </h1>
    </body>

</html>

templates/app/confirm_expired.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>FEEDBACKER</title>        
    </head>

    <body>    
    <a href="/">Main page</a><br />
    <h1>Сорян, но срок действия ссылки активации истек</h1>
    </body>

</html>

templates/app/index_backup.html
<!DOCTYPE html>
{% load staticfiles %}
    <head>
        <title>FEEDBACKER</title>
        <link rel = "stylesheet" href="{% static "app/css/base.css" %}" />
        <script src="{% static "app/scripts/jquery.js" %}"></script>
    </head>
    <body>
    {{something_cool}} <br/>
    <h1>Внимание, база данных дропается каждый день, так что то, что ваш аккаунт исчез - это норма. Можете писать админу, если хотите - он пригласит вас на чашку чая. Если, конечно, вы адрес этого админа найдете</h1>
    {% if user.is_authenticated %}
        <h1>Добро пожаловать, {{user.username}} !!!</h1>
        <a href="/my/">My Feedbacker</a><br />
        <a href="/logout">Выйти</a><br />
    {% else %}        
    <h1> Добро пожаловать в feedbacker!</h1>    
    <p>Войдите </p>
     <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            Логин: <input type="text" name="username" value="" size="50" />
            <br />
            Пароль: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="Вход!" />
        </form><br />        
    или <a href = "/register/"> зарегистрируйтесь</a> <br />
    {% endif %}
        <h3>Недавно зарегистрированные студенты: </h3><br />         
         {% if students %}
            
            <ul>
                {% for student in students %}
                <li> {{ student.user.first_name }} {{ student.user.last_name }}, {{ student.group.name }} </li>
                {% endfor %}
            </ul>
            {% else %}
                Пока еще никто не зарегистрировался. <br/>
            {% endif %}         
        <h3>Недавно зарегистрированные преподаватели: </h3><br />         
        {% if instructors %}            
            <ul>
                {% for instructor in instructors %}
                <li> {{ instructor.user.last_name }} {{ instructor.user.first_name }}, {{ instructor.middle_name }} </li>
                {% endfor %}
            </ul>
            {% else %}
                Пока еще никто не зарегистрировался. <br/>
            {% endif %}         
    <a href = "/about_us/">О нас</a><br/>
    <a href = "/about_feedbacker">О приложении</a><br/>
         <img src='{% static "app/pictures/yasdelal.png" %}' alt="Ya sdelal'" />

    </body>


</html>

templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

templates/app/login.html
<!DOCTYPE html>
<html>

    <head>       
        <title>Feedbacker</title>
    </head>

    <body>
        <h1>Login to Feedbacker</h1>

        <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>

    </body>
</html>

templates/app/my.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>FEEDBACKER</title>
        <link rel = "stylesheet" href="{% static "app/css/base.css" %}" />
        <script src="{% static "app/scripts/jquery.js" %}"></script>
    </head>

    <body>
    <h1>Добро пожаловать обратно, {{user.username}} !!!</h1>               
    <a href="/logout">Выйти</a><br />                  
    <a href="/">На главную</a><br />
    <p> Сегодня: {{ today }}</p>
    <h2> Ваш профиль </h2>
    <p> Тип аккаунта: {{ account_type}} </p>     
    <p> Email: {{user.email}}    </p>
    {% if student_info %}
    <p> Группа: {{ student_info.student.group }}</p>        
    <p> Ваши предметы: </p>        
          {% if student_info.s_to_l %}            
            <ul>
            {% for key,value in student_info.s_to_l %}            
                <li><b>{{ key }}</b></li>                            
                {% if value %}
                Прошедшие лекции:<br/>
                <ul>
                    {% for lec in value %}                        
                        <li> {{ lec }}, {{ lec.datetime }} </li>
                    {% endfor %}
                </ul>
                {% else %}
                    Лекции пока не добавлены.
                {% endif %}
            {% endfor %}
            </ul>                                        
        {% else %}
            Предметы для вашей группы еще не добавлены. <br/>
        {% endif %}     
    {% endif %}     
    {% if instructor_info %}   
    Вы преподаватель
    {% endif %}          
    {% if admin_info %}   
    Вы админ
    {% endif %}          
    </body>

</html>

templates/app/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Password reset complete{% endblock %}

{% block content %}
<p>Your password has been set.  You may go ahead and log in now.</p>
<p><a href="{{ login_url }}">Log in</a></p>
{% endblock %}

templates/app/password_reset_email.html
{% autoescape off %}
You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'django.contrib.auth.views.password_reset_confirm' uidb64=uid, token=token %}
{% endblock %}

Your username, in case you've forgotten: {{ user.username }}

Thanks for using our site!

The {{ site_name }} team.

{% endautoescape %}

templates/app/student_account.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>FEEDBACKER</title>
        <link rel = "stylesheet" href="{% static "app/css/base.css" %}" />
        <script src="{% static "app/scripts/jquery.js" %}"></script>
    </head>

    <body>
    <h1>Добро пожаловать обратно, {{user.username}} !!!</h1>               
    <a href="/logout">Выйти</a><br />                  
    <a href="/">На главную</a><br />
    <p> Сегодня: {{ today }}</p>
    <h2> Ваш профиль </h2>
    <p> Тип аккаунта: {{ user.get_profile_type_display }} </p>     
    <p> Email: {{user.email}} </p>        
    {% if user.st_profile.group %}    
    <p> Группа: {{ user.st_profile.group }}
    {% else %}
    <p> Вы не привязаны ни к одной из групп </p>
    {% endif %}        

    <p> Номер студенческого: {{ user.st_profile.student_id }}</p>  


 
    </body>

</html>