DjangoWebProject/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from app.models import CustomUser, GTSIL_Results_Distribution
from rest_framework import routers, serializers, viewsets
from django.utils.translation import ugettext_lazy as _
import django_filters
from rest_framework import filters
from rest_framework import generics


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = CustomUser
        fields = ('url', 'username', 'is_staff', 'status_confirmed')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

"""
class UserSerializer(serializers.Serializer):
    email = serializers.EmailField()
    username = serializers.CharField(max_length=100)

class CommentSerializer(serializers.Serializer):
    user = UserSerializer()
    content = serializers.CharField(max_length=200)
    created = serializers.DateTimeField()
"""

class GroupSerializer(serializers.Serializer):
    name = serializers.CharField(max_length = 100)

class LectureSerializer(serializers.Serializer):
    lecture_start_time = serializers.DateTimeField()

class SubjectSerializer(serializers.Serializer):
    full_name = serializers.CharField(max_length = 100)
    subject_id = serializers.CharField(max_length=10)
class InstructorSerializer(serializers.Serializer):
    cist_id = serializers.CharField(max_length=5)
    last_name = serializers.CharField(max_length = 50)
    first_name = serializers.CharField(max_length = 50)
    middle_name = serializers.CharField(max_length = 50)
class CriteriaSerializer(serializers.Serializer):
    criteria_name = serializers.CharField(max_length=100)

class GTSILResultDistributionSerializer(serializers.HyperlinkedModelSerializer):
    lecture = LectureSerializer()
    group = GroupSerializer()
    subject = SubjectSerializer()
    instructor = InstructorSerializer()
    criteria = CriteriaSerializer()

    class Meta:
        model = GTSIL_Results_Distribution

class GTSILResultDistributionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = GTSIL_Results_Distribution.objects.all()
    serializer_class = GTSILResultDistributionSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('instructor', 'criteria','group', 'subject', 'lecture__gtsi__activity_type')
"""
class GTSILResultDistributionQueryViewSet(viewsets.ModelViewSet):
    queryset = GTSIL_Results_Distribution.objects.all()
    serializer_class = GTSILResultDistributionSerializer
    def get_querysety(self):
"""

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
#router.register(r'users', UserViewSet)
router.register(r'distributions', GTSILResultDistributionViewSet)
#router.register(r'distributions/subject=(?P<subject_id>.+)/(?P<instructor_id>.+)/(?P<activity_id>.+)$', GTSILResultDistributionQueryViewSet)

# Uncomment the next lines to enable the admin:
admin.autodiscover()

urlpatterns = [
    url(r'^', include('app.urls', namespace="main")),
    url(r'^', include('news.urls', namespace="news")),
    url(r'^',include('blog.urls', namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^apiz/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

app/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from django.views.generic import TemplateView
from app.views import (Index, Register, UserLogin, 
    RegisterStudent, RegisterInstructor, 
    AboutFeedbacker, AboutUs, 
    My, UserLogout, RegisterConfirm,
    ConfirmStatus, AttachGroup,
    EvaluateLecture, EvaluateSubject,
    FindProfile, AttachProfile,
    LectureResults, LectureResultsGraphData, SubjectResults,
    SubjectResultsGraphData, GroupsAndCriteria, Faq, ContactAdmin,
    TakeSurvey, ShowGroupInfo, MyProfile, Tutorials, TestResults,
    RefreshSchedule, StudentRatingView, OpenStudentRating, EditStudentRating,
    DeleteStudentRating, ShowComplaints)
from app.api import GTSILFeedback, Subjects
from app.views import email_exists, username_exists
from django.utils.translation import ugettext_lazy as _
from rest_framework import routers
from app import api
# Uncomment the next lines to enable the admin:
admin.autodiscover()
router = routers.DefaultRouter()
router.register(r'users', api.UserViewSet)
router.register(r'groups', api.GroupViewSet)

urlpatterns = patterns('',
    # Examples:
    url(r'^$', Index.as_view(), name = 'index'),    
    url(r'^login/$', UserLogin.as_view(), name = 'login'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls'), name = 'admin_doc'),

    # Uncomment the next line to enable the admin:
    url(r'^register/$', Register.as_view(), name = 'register'),
    url(r'^register/', include(patterns('',
        url(r'^student/$', RegisterStudent.as_view(), name = 'register_student'),
        url(r'^instructor/$', RegisterInstructor.as_view(), name = 'register_instructor'),
    ))),
    # url(r'^register_student/$', RegisterStudent.as_view(), name = 'register_student'),
    # url(r'^register_instructor/$', RegisterInstructor.as_view(), name = 'register_instructor'),
    url(r'^confirm_status/$', ConfirmStatus.as_view(), name = 'confirm_status'),
    url(r'^attach_group/$', AttachGroup.as_view(), name = 'attach_group'),
    url(_(r'^my/$'), My.as_view(), name = 'my'),
    url(r'^logout/$', UserLogout.as_view(), name = 'logout'),
    url(r'^about_us/$', AboutUs.as_view(), name = 'about_us'),
    url(r'^contact_admin/', ContactAdmin.as_view(), name = 'contact_admin'),
    url(r'^faq/$', Faq.as_view(), name='faq'),
    url(r'^about_feedbacker/$', AboutFeedbacker.as_view(), name = 'about_feedbacker'),            
    url(r'^admin/', include(admin.site.urls), name = 'admin'),
    url(r'^confirm/(?P<activation_key>\w+)/', RegisterConfirm.as_view(), name = 'confirm'),
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'registration/password_reset_form.html', 'post_reset_redirect' : '/user/password/reset/done/'}, name="password_reset"),
    (r'^user/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm', 
        {'post_reset_redirect' : '/user/password/done/'}),
    (r'^user/password/done/$',
        'django.contrib.auth.views.password_reset_complete'),
    url(r'^subjects/(?P<gtsi_id>\d+)/$', EvaluateSubject.as_view(), name='subject'),
    url(r'^subjects/(?P<gtsi_id>\d+)/vote/$', EvaluateSubject.as_view(), name='vote_subject'),
    url(r'^lectures/(?P<gtsil_id>\d+)/$', EvaluateLecture.as_view(), name='lecture'),
    url(r'^lectures/vote/(?P<gtsil_id>\d+)/$', EvaluateLecture.as_view(), name='vote_lecture'),
    url(r'^username_exists/(?P<username>([A-Z]|[a-z]|[0-9]|\.|_|\-){3,30})$', username_exists),
    url(r'^email_exists/(?P<email>([A-Z]|[a-z]|[0-9]|\@|\.|_|\-){3,30})$', email_exists),
    url(r'^find_profile/$', FindProfile.as_view(), name = 'find_profile'),
    url(r'^attach_profile/(?P<instructor_id>\d+)/$', AttachProfile.as_view(), name = 'attach_profile'),
    url(r'^results/(?P<gtsil_id>\d+)/$', LectureResults.as_view(), name='lecture_results'),
    url(r'^subject_results/(?P<subject_id>\d+)/$', SubjectResults.as_view(), name='subject_results'),
    url(r'^graphdata/$', LectureResultsGraphData.as_view(), name='graphdata'),
    url(r'^subjgraphdata/$', SubjectResultsGraphData.as_view(), name = 'subjgraphdata'),
    url(r'^getgroupscrit/$', GroupsAndCriteria.as_view(), name='getgroupscrit'),
    url(r'^api/v1/lectures/(?P<gtsil_id>\d+)/$', GTSILFeedback.as_view(), name='gtsil_feedback_api'),
    url(r'^api/v1/subjects/$', Subjects.as_view(), name='subjects_api'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^surveys/(?P<survey_id>\w+-\w+-\w+-\w+-\w+)/$', TakeSurvey.as_view(), name = 'survey'),
    url(r'^group/(?P<group_id>\w+)/$', ShowGroupInfo.as_view(), name = 'group_info'),
    url(r'^my/profile/$', MyProfile.as_view(), name = 'my_profile'),
    url(r'^tutorials/$', Tutorials.as_view(), name = 'tutorials'),
    url(r'^survey_results/(?P<survey_id>\w+-\w+-\w+-\w+-\w+)/(?P<group_id>\d+)/$', TestResults.as_view(), name = 'survey_results'),
    url(r'^refresh_schedule/$', RefreshSchedule.as_view(), name = 'refresh_schedule'),
    url(r'^student_rating/$', StudentRatingView.as_view(), name='student_rating'),
    url(r'^open_student_rating/$', OpenStudentRating.as_view(), name='open_student_rating'),
    url(r'^edit_student_rating/(?P<rating_id>\d+)/$', EditStudentRating.as_view(), name='edit_student_rating'),
    url(r'^delete_student_rating/(?P<rating_id>\d+)/$', DeleteStudentRating.as_view(), name='delete_student_rating'),
    url(r'^show_complaints/$', ShowComplaints.as_view(), name='show_complaints'),
    # url(r'^confirm_status_page/$', ConfirmStatusPage.as_view(), name="confirm_status_page"),
)

blog/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from django.views.generic import TemplateView
from blog.views import (Blog, CreateBlogView, BlogPostView, UpdateBlogPostView,
    DeleteBlogPostView, UpdateCommentView, DeleteCommentView)
from django.utils.translation import ugettext_lazy as _

# Uncomment the next lines to enable the admin:
admin.autodiscover()


urlpatterns = patterns('',
	url(r'^blog/$', Blog.as_view(), name='blog',),
    url(r'^new$', CreateBlogView.as_view(), name='blog-new',),
    url(r'^(?P<pk>\d+)/$', BlogPostView.as_view(), name='blogpost-view',),
    url(r'^edit/(?P<pk>\d+)/$', UpdateBlogPostView.as_view(), name='blogpost-edit',),
    url(r'^(?P<blogpost_id>\d+)/edit_comment/(?P<pk>\d+)/$', UpdateCommentView.as_view(), name='comment-edit',),
    url(r'^delete/(?P<pk>\d+)/$', DeleteBlogPostView.as_view(), name='blogpost-delete',),
    url(r'^(?P<blogpost_id>\d+)/delete-comment/(?P<pk>\d+)/$', DeleteCommentView.as_view(), name='comment-delete',),)

news/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from django.views.generic import TemplateView

from django.utils.translation import ugettext_lazy as _
from rest_framework import routers
from news.views import News, NewsPieceView, UpdateNewsPieceView, DeleteNewsPieceView, CreateNewsPieceView
# Uncomment the next lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^news/$', News.as_view(), name='news',),
    url(r'^news/(?P<pk>\d+)/$', NewsPieceView.as_view(), name='newspiece-view',),
    url(r'^news/edit/(?P<pk>\d+)/$', UpdateNewsPieceView.as_view(), name='newspiece-edit',),
    url(r'^news/delete/(?P<pk>\d+)/$', DeleteNewsPieceView.as_view(), name='newspiece-delete',),
    url(r'^news/new$', CreateNewsPieceView.as_view(), name='newspiece-new',),)

blog/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from app.models import CustomUser
# Create your models here.

class Tag(models.Model):
	tag = models.CharField(max_length=50)
	def save(self, *args, **kwargs):
		if isinstance(self.tag, str):
			self.tag = self.tag.decode("utf-8")
		super(Tag, self).save(*args, **kwargs)
	class Meta:
		verbose_name = u'Тег'
		verbose_name_plural = u'Теги'

class BlogPost(models.Model):
	title = models.CharField(max_length = 200)
	author = models.ForeignKey(CustomUser)
	body = models.TextField()
	timestamp = models.DateTimeField()
	tag = models.ManyToManyField(Tag, blank = True)
	def save(self, *args, **kwargs):
		if isinstance(self.title, str):
			self.title = self.title.decode("utf-8")
		if isinstance(self.body, str):
			self.body = self.body.decode("utf-8")
		super(BlogPost, self).save(*args, **kwargs)	
	def get_absolute_url(self):
		return reverse('blog:blogpost-view', kwargs={'pk': self.id})

class Comment(models.Model):
	blogpost = models.ForeignKey(BlogPost)
	author = models.ForeignKey(CustomUser)
	title = models.CharField(max_length=200)
	body = models.TextField()
	timestamp = models.DateTimeField()
	parent_comment = models.ForeignKey("self", blank = True, null = True, default = None)
	def save(self, *args, **kwargs):
		if isinstance(self.title, str):
			self.title = self.title.decode("utf-8")
		if isinstance(self.body, str):
			self.body = self.body.decode("utf-8")
		super(Comment, self).save(*args, **kwargs)	

blog/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

# Стандартные библиотеки
from __future__ import unicode_literals
import re
import datetime

# Библиотеки Джанго
#from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.utils import timezone

# Импорт каптчи
#from nocaptcha_recaptcha.fields import NoReCaptchaField

# Локальные импорты 
from blog.models import BlogPost, Comment

class CreatePostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ('title', 'body',)
		widgets = {
		'title': forms.TextInput(attrs={'class': 'form-control'}),
		'body': forms.Textarea(attrs={'class': 'form-control'}),
		}
		labels = {
		'title':_(u'Название поста'),
		'body':_(u'Тест поста'),
		}

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('title', 'body')
		widgets = {
		'title': forms.TextInput(attrs={'class': 'form-control'}),
		'body': forms.Textarea(attrs={'class': 'form-control'}),		
		}
		labels = {
		'title':_(u'Тема'),
		'body':_(u'Мысль полностью'),
		}

blog/templates/blog/blog_update_form.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

blog/templates/blog/blogpost.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{{ blogpost.title }}{% endblock %}

{% block scripts %} 
<script>$('#about_us_li').addClass('active');</script> 
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-2 col-sm-2 col-xs-0"></div>
    <div class="col-lg-8 col-sm-8 col-xs-12">
        <div class="panel-body">
            <div class="btn-group">
                <a href="{% url 'blog:blog' %}"><button class="btn btn-default" title="Передумал">Обратно к списку постов</button></a>
            </div>
            <div class="blog">
                <div class="blog-post">
                    <div class="blog-post-header">
                        <div class="blog-post-title">{{ blogpost.title }}</div>
                        <div class="blog-post-author">{{ blogpost.author }}</div>
                        <div class="blog-post-date">{{ blogpost.timestamp  }}</div>
                        
                        {% if blogpost.author == user %}

                        <a href="{% url 'news:newspiece-edit' pk=blogpost.id %}"><span class="glyphicon glyphicon-pencil"></span></a>

                        <a data-toggle="modal" data-target="#myModal" href="#"><span class="glyphicon glyphicon-remove" style="color:#B80000;"></span></a>

                        <!-- Modal -->
                        <div class="modal fade" id="myModal" role="dialog">
                            <div class="modal-dialog">

                              <!-- Modal content-->
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                  <h4 class="modal-title">Удаление новости</h4>
                              </div>
                              <div class="modal-body">
                                  <p>Вы уверены, что хотите удалить эту новость?</p>
                              </div>
                              <div class="modal-footer">
                               <div class="execute_block">
                                <form action="{% url 'news:newspiece-delete' pk=blogpost.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary" id="save_blog" title="Удалить">Удалить</button>    
                                </form>
                            </div>
                            <div class="go_back_block">
                                <button class="btn btn-default" title="Передумал" data-dismiss="modal">Передумал!</button>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>


    </a>
    {% endif %}

    {% autoescape off %}
    <div class="blog-post-body">{{ blogpost.body }}</div>
    {% endautoescape %}
</div>
<div id="comments-block">
    {% if comments %}
    {% for comm in blogpost.comment_set.all %}

    {% if comment.id and comment.id == comm.id %}
    {% if form %}
    <form method="post" action="{{ action }}">
        {% csrf_token %}

        {{ form }}
        <div class="btn-group" id="sbutton_wrapper">
            <button type="submit" class="btn btn-primary" id="save_blog" title="Сохранить">Сохранить</button>                  
        </div>

    </form>
    <div class="btn-group" id="sbutton_wrapper">
        <a href="{% url 'blog:blogpost-view' pk=blogpost.id %}"><button class="btn btn-primary" id="save_blog" title="Сохранить">Отмена</button></a>
    </div>                
    {% endif %}
    {% else %}
    <p>{{ comm.title }}</p>
    <p>Действия: 
        {% if comm.author == user %}
        <a href="{% url 'blog:comment-edit' blogpost_id=blogpost.id pk=comm.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a href="{% url 'blog:comment-delete' blogpost_id=blogpost.id pk=comm.id %}"><span class="glyphicon glyphicon-remove" style="color:#B80000;"></span></span></a>
        {% else %}
        <span class="glyphicon glyphicon-pencil"></span>
        {% endif %}
    </p>
    <p> {{ comm.author }}, {{ comm.timestamp.date }}</p>
    <p>{{ comm.body }}</p>

    {% endif %}

    {% endfor %}
    {% else %}
    <p><i>Комментариев пока нет.</i></p>
    {% endif %}
</div>
{% if not comment.id %}
{% if form %}
<br/><p>Написать комментарий:</p>
<form method="post" action="{{ action }}">
    {% csrf_token %}

    {{ form }}
    <div class="btn-group" id="sbutton_wrapper">
        <button type="submit" class="btn btn-primary" id="save_blog" title="Сохранить">Сохранить</button>                  
    </div>

</form>
{% endif %}
{% endif %}
</div>
</div>
</div>
<div class="col-lg-2 col-sm-2 col-xs-0"></div>
</div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Блог разработчиков{% endblock %}

{% block scripts %} 
<script>$('#about_us_li').addClass('active');</script> 
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-2 col-sm-2 col-xs-0"></div>
    <div class="col-lg-8 col-sm-8 col-xs-12">
        <div class="panel-body">
            {% if perms.app.add_blogpost %}
            <div class="btn-group">
                <a href="{% url 'blog:blog-new' %}"><button class="btn btn-primary" id="submit" title="Новый пост">Новый пост</button></a>
            </div>
            {% endif %}
            <div class="blog">
                {% for post in object_list %}
                <div class="blog-post">
                    <div class="blog-post-header">
                        <div class="blog-post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></div>
                        <div class="blog-post-author">{{ post.author }}</div>
                        <div class="blog-post-date">{{ post.timestamp.date }}</div>
                        {% if user == post.author %}

                        <a href="{% url 'blog:blogpost-edit' pk=post.id %}"><span class="glyphicon glyphicon-pencil"></span></a>

                        <a data-toggle="modal" data-target="#myModal" href="#"><span class="glyphicon glyphicon-remove" style="color:#B80000;"></span></a>

                        <!-- Modal -->
                        <div class="modal fade" id="myModal" role="dialog">
                            <div class="modal-dialog">

                              <!-- Modal content-->
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                  <h4 class="modal-title">Удаление поста</h4>
                              </div>
                              <div class="modal-body">
                                  <p>Вы уверены, что хотите удалить эту запись?</p>
                              </div>
                              <div class="modal-footer">
                                 <div class="execute_block">
                                    <form action="{% url 'blog:blogpost-delete' pk=post.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-primary" id="save_blog" title="Удалить">Удалить</button>    
                                    </form>
                                </div>
                                <div class="go_back_block">
                                    <button class="btn btn-default" title="Передумал" data-dismiss="modal">Передумал!</button>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
  


<!---

                        <a href="{% url 'blog:blogpost-delete' pk=post.id %}"><span class="glyphicon glyphicon-remove" style="color:#B80000;"></span>
-->




                        </a>
                        {% endif %}
                    </div>
                    {% autoescape off %}
                    <div class="blog-post-body shrinked" id="blog-post-body_{{ forloop.counter }}">{{ post.body }}</div>
                    <script>
                        blog_post_body_current = document.getElementById("blog-post-body_{{ forloop.counter }}");
                        bpost_max_length = 500;
                        new_read_full_button = document.createElement("div");

                        new_read_full_button.className = "blog-post-show-full";
                        new_read_full_button.innerHTML = "<a href='{{ post.get_absolute_url }}'><button class='btn btn-default' title='Перейти к просмотру полной версии поста'>Читать дальше →</button></a>"; 
                        if (blog_post_body_current.innerHTML.length > bpost_max_length)
                        {
                            blog_post_body_current.innerHTML = blog_post_body_current.innerHTML.substr(0, bpost_max_length - 4) + " …";
                            blog_post_body_current.parentNode.insertBefore(new_read_full_button, blog_post_body_current.nextSibling);
                        }
                        blog_post_body_current.classList.add("ready");
                    </script>
                    {% endautoescape %}
                    <br /><p>Комментарии: <a href="{{ post.get_absolute_url }}#comments-block"><span class="label label-default">{{ post.comment_set.count }}</span></a></p>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="text-center">
            <ul class="pagination">
                {% if object_list.has_previous %}
                <li><a href="?page=1" title="Самое новое"><span>&lt&lt</span></a></li>
                <li><a href="?page={{ object_list.previous_page_number }}" title="Новее">&lt</a></li>
                {% endif %}


                {% for page_num in object_list.paginator.page_range %}
                <!-- Если это текущая страница, то отображаем ее обязательно, и думаем, что делать вокруг -->
                {% if object_list.number == page_num %}
                <!-- Если номер страницы больше 4, то есть 5 и выше, то отображаем троеточие и номер предыдущей страницы -->
                {% if page_num > 4 %}
                {% if page_num > 5 %}
                <li><a href="?page={{ object_list.previous_page_number|add:'-1' }}" title="Новее">...</a></li>
                {% endif %}
                <li><a href="?page={{ object_list.previous_page_number }}" title="Новее">{{ object_list.previous_page_number }}</a></li>
                {% endif %}
                <li class="active"><a href="?page={{ page_num }}" onclick="return false;">{{ page_num }}</a></li>

                {% if page_num > 4 and page_num != object_list.paginator.num_pages|add:'-1' and object_list.has_next %}
                <li><a href="?page={{ object_list.next_page_number }}" title="Старее">{{ object_list.next_page_number }}</a></li>
                {% if page_num < object_list.paginator.num_pages|add:'-2' %}
                <li><a href="?page={{ object_list.next_page_number|add:'1' }}" title="Старее">...</a></li>
                {% endif %}
                {% endif %}


                {% else %}
                <!-- Отображаем номера страниц от 1 до 3 -->
                    {% if page_num < 4 %}
                    <li><a href="?page={{ page_num }}"> {{ page_num }}</a></li>
                    {% endif %}
                    {% if page_num == 4 and object_list.number < 3 and object_list.paginator.num_pages > 4 %}
                    <li><a href="?page={{ page_num }}">... </a></li>
                    {% endif %}
                <!-- Если рисуем 4-ю страницу, а находимся на третьей -->
                    {% if page_num == 4 and object_list.number == 3 and object_list.paginator.num_pages > 4 %}
                    <li><a href="?page={{ page_num }}"> {{ page_num }} </a></li>
                <!-- Елсли при этом следующая страница существует, то отображаем ее -->
                    {% if page_num|add:'1' <= object_list.paginator.num_pages and object_list.paginator.num_pages > 5 %}
                    <li><a href="?page={{ page_num|add:'1' }}"> ... </a></li>
                    {% endif %}
                    {% endif %}

                    {% if page_num == 5 and object_list.number == 4 and object_list.paginator.num_pages > 5 %}
                    <li><a href="?page={{ page_num }}"> {{ page_num }} </a></li>
                     {% if page_num|add:'1' <= object_list.paginator.num_pages and object_list.paginator.num_pages > 6 %}
                    <li><a href="?page={{ page_num|add:'1' }}"> ... </a></li>
                    {% endif %}
                    {% endif %}

                    {% if page_num == object_list.paginator.num_pages and object_list.paginator.num_pages > 3 %}
                    <li><a href="?page={{ page_num }}"> {{ page_num }}</a></li>
                    {% endif %}
                {% endif %}
                {% endfor %}

                
                {% if object_list.has_next %}
                <li><a href="?page={{ object_list.next_page_number }}" title="Старее">&gt</a></li>
                <li><a href="?page={{ object_list.paginator.num_pages }}" title="Самое старое"><span>&gt&gt</span></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="col-lg-2 col-sm-2 col-xs-0"></div>
</div>
{% endblock %}