DjangoWebProject/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from app.models import CustomUser, GTSIL_Results_Distribution
from rest_framework import routers, serializers, viewsets
from django.utils.translation import ugettext_lazy as _
import django_filters
from rest_framework import filters
from rest_framework import generics


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = CustomUser
        fields = ('url', 'username', 'is_staff', 'status_confirmed')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

"""
class UserSerializer(serializers.Serializer):
    email = serializers.EmailField()
    username = serializers.CharField(max_length=100)

class CommentSerializer(serializers.Serializer):
    user = UserSerializer()
    content = serializers.CharField(max_length=200)
    created = serializers.DateTimeField()
"""

class GroupSerializer(serializers.Serializer):
    name = serializers.CharField(max_length = 100)

class LectureSerializer(serializers.Serializer):
    lecture_start_time = serializers.DateTimeField()

class SubjectSerializer(serializers.Serializer):
    full_name = serializers.CharField(max_length = 100)
    subject_id = serializers.CharField(max_length=10)
class InstructorSerializer(serializers.Serializer):
    cist_id = serializers.CharField(max_length=5)
    last_name = serializers.CharField(max_length = 50)
    first_name = serializers.CharField(max_length = 50)
    middle_name = serializers.CharField(max_length = 50)
class CriteriaSerializer(serializers.Serializer):
    criteria_name = serializers.CharField(max_length=100)

class GTSILResultDistributionSerializer(serializers.HyperlinkedModelSerializer):
    lecture = LectureSerializer()
    group = GroupSerializer()
    subject = SubjectSerializer()
    instructor = InstructorSerializer()
    criteria = CriteriaSerializer()

    class Meta:
        model = GTSIL_Results_Distribution

class GTSILResultDistributionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = GTSIL_Results_Distribution.objects.all()
    serializer_class = GTSILResultDistributionSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('instructor', 'criteria','group', 'subject', 'lecture__gtsi__activity_type')
"""
class GTSILResultDistributionQueryViewSet(viewsets.ModelViewSet):
    queryset = GTSIL_Results_Distribution.objects.all()
    serializer_class = GTSILResultDistributionSerializer
    def get_querysety(self):
"""

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
#router.register(r'users', UserViewSet)
router.register(r'distributions', GTSILResultDistributionViewSet)
#router.register(r'distributions/subject=(?P<subject_id>.+)/(?P<instructor_id>.+)/(?P<activity_id>.+)$', GTSILResultDistributionQueryViewSet)

# Uncomment the next lines to enable the admin:
admin.autodiscover()

urlpatterns = [
    url(r'^', include('app.urls', namespace="main")),
    url(r'^', include('news.urls', namespace="news")),
    url(r'^',include('blog.urls', namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^apiz/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

app/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from django.views.generic import TemplateView
from app.views import (Index, Register, UserLogin, 
    RegisterStudent, RegisterInstructor, 
    AboutFeedbacker, AboutUs, 
    My, UserLogout, RegisterConfirm,
    ConfirmStatus, AttachGroup,
    EvaluateLecture, EvaluateSubject,
    FindProfile, AttachProfile,
    LectureResults, LectureResultsGraphData, SubjectResults,
    SubjectResultsGraphData, GroupsAndCriteria, Faq, ContactAdmin,
    TakeSurvey, ShowGroupInfo, MyProfile, Tutorials, TestResults,
    RefreshSchedule, StudentRatingView, OpenStudentRating, EditStudentRating,
    DeleteStudentRating, ShowComplaints)
from app.api import GTSILFeedback, Subjects
from app.views import email_exists, username_exists
from django.utils.translation import ugettext_lazy as _
from rest_framework import routers
from app import api
# Uncomment the next lines to enable the admin:
admin.autodiscover()
router = routers.DefaultRouter()
router.register(r'users', api.UserViewSet)
router.register(r'groups', api.GroupViewSet)

urlpatterns = patterns('',
    # Examples:
    url(r'^$', Index.as_view(), name = 'index'),    
    url(r'^login/$', UserLogin.as_view(), name = 'login'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls'), name = 'admin_doc'),

    # Uncomment the next line to enable the admin:
    url(r'^register/$', Register.as_view(), name = 'register'),
    url(r'^register/', include(patterns('',
        url(r'^student/$', RegisterStudent.as_view(), name = 'register_student'),
        url(r'^instructor/$', RegisterInstructor.as_view(), name = 'register_instructor'),
    ))),
    # url(r'^register_student/$', RegisterStudent.as_view(), name = 'register_student'),
    # url(r'^register_instructor/$', RegisterInstructor.as_view(), name = 'register_instructor'),
    url(r'^confirm_status/$', ConfirmStatus.as_view(), name = 'confirm_status'),
    url(r'^attach_group/$', AttachGroup.as_view(), name = 'attach_group'),
    url(_(r'^my/$'), My.as_view(), name = 'my'),
    url(r'^logout/$', UserLogout.as_view(), name = 'logout'),
    url(r'^about_us/$', AboutUs.as_view(), name = 'about_us'),
    url(r'^contact_admin/', ContactAdmin.as_view(), name = 'contact_admin'),
    url(r'^faq/$', Faq.as_view(), name='faq'),
    url(r'^about_feedbacker/$', AboutFeedbacker.as_view(), name = 'about_feedbacker'),            
    url(r'^admin/', include(admin.site.urls), name = 'admin'),
    url(r'^confirm/(?P<activation_key>\w+)/', RegisterConfirm.as_view(), name = 'confirm'),
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'registration/password_reset_form.html', 'post_reset_redirect' : '/user/password/reset/done/'}, name="password_reset"),
    (r'^user/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm', 
        {'post_reset_redirect' : '/user/password/done/'}),
    (r'^user/password/done/$',
        'django.contrib.auth.views.password_reset_complete'),
    url(r'^subjects/(?P<gtsi_id>\d+)/$', EvaluateSubject.as_view(), name='subject'),
    url(r'^subjects/(?P<gtsi_id>\d+)/vote/$', EvaluateSubject.as_view(), name='vote_subject'),
    url(r'^lectures/(?P<gtsil_id>\d+)/$', EvaluateLecture.as_view(), name='lecture'),
    url(r'^lectures/vote/(?P<gtsil_id>\d+)/$', EvaluateLecture.as_view(), name='vote_lecture'),
    url(r'^username_exists/(?P<username>([A-Z]|[a-z]|[0-9]|\.|_|\-){3,30})$', username_exists),
    url(r'^email_exists/(?P<email>([A-Z]|[a-z]|[0-9]|\@|\.|_|\-){3,30})$', email_exists),
    url(r'^find_profile/$', FindProfile.as_view(), name = 'find_profile'),
    url(r'^attach_profile/(?P<instructor_id>\d+)/$', AttachProfile.as_view(), name = 'attach_profile'),
    url(r'^results/(?P<gtsil_id>\d+)/$', LectureResults.as_view(), name='lecture_results'),
    url(r'^subject_results/(?P<subject_id>\d+)/$', SubjectResults.as_view(), name='subject_results'),
    url(r'^graphdata/$', LectureResultsGraphData.as_view(), name='graphdata'),
    url(r'^subjgraphdata/$', SubjectResultsGraphData.as_view(), name = 'subjgraphdata'),
    url(r'^getgroupscrit/$', GroupsAndCriteria.as_view(), name='getgroupscrit'),
    url(r'^api/v1/lectures/(?P<gtsil_id>\d+)/$', GTSILFeedback.as_view(), name='gtsil_feedback_api'),
    url(r'^api/v1/subjects/$', Subjects.as_view(), name='subjects_api'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^surveys/(?P<survey_id>\w+-\w+-\w+-\w+-\w+)/$', TakeSurvey.as_view(), name = 'survey'),
    url(r'^group/(?P<group_id>\w+)/$', ShowGroupInfo.as_view(), name = 'group_info'),
    url(r'^my/profile/$', MyProfile.as_view(), name = 'my_profile'),
    url(r'^tutorials/$', Tutorials.as_view(), name = 'tutorials'),
    url(r'^survey_results/(?P<survey_id>\w+-\w+-\w+-\w+-\w+)/(?P<group_id>\d+)/$', TestResults.as_view(), name = 'survey_results'),
    url(r'^refresh_schedule/$', RefreshSchedule.as_view(), name = 'refresh_schedule'),
    url(r'^student_rating/$', StudentRatingView.as_view(), name='student_rating'),
    url(r'^open_student_rating/$', OpenStudentRating.as_view(), name='open_student_rating'),
    url(r'^edit_student_rating/(?P<rating_id>\d+)/$', EditStudentRating.as_view(), name='edit_student_rating'),
    url(r'^delete_student_rating/(?P<rating_id>\d+)/$', DeleteStudentRating.as_view(), name='delete_student_rating'),
    url(r'^show_complaints/$', ShowComplaints.as_view(), name='show_complaints'),
    # url(r'^confirm_status_page/$', ConfirmStatusPage.as_view(), name="confirm_status_page"),
)

app/templates/app/confirm.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Успех{% endblock %}

{% block content %}
<div class="col-lg-3 col-sm-2 col-xs-0"></div>
<div class="col-lg-6 col-sm-8 col-xs-12">
    <div class="panel panel-info">
        <div class="panel-heading"><h4>Аккаунт успешно активирован.</h4></div>
        <div class="panel-body">
            <p>Все в порядке, ваш аккаунт активирован, можете уже, наконец, войти.<br/>
            Для возврата на главную страницу нажмите <a href="{% url 'main:index' %}">здесь</a>.</p>
        </div>
    </div>
</div>
<div class="col-lg-3 col-sm-2 col-xs-0"></div>
{% endblock %}

app/templates/app/confirm_expired.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Ошибка подтверждения{% endblock %}

{% block content %}
<div class="col-lg-3 col-sm-2 col-xs-0"></div>
<div class="col-lg-6 col-sm-8 col-xs-12">
    <div class="panel panel-info">
        <div class="panel-heading"><h4>Cрок действия ссылки активации истек.</h4></div>
        <div class="panel-body">
            <p>Для возврата на главную страницу нажмите <a href="{% url 'main:index' %}">здесь</a>.</p>
        </div>
    </div>
</div>
<div class="col-lg-3 col-sm-2 col-xs-0"></div>
{% endblock %}

app/templates/app/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Feedbacker{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'app/css/pages/index.css' %}">
{% endblock %}

{% block scripts %}
<script>
    $('#main_li').addClass('active');
    var jquery_mobile_js_url = "{% static 'app/scripts/jquery.mobile.custom.min.js' %}";
</script>
<script type="text/javascript" src='{% static "app/scripts/pages/index.js" %}'></script>
{% endblock %}

{% block content %}
<div id="main-box" class="main-box">
    <section class="main-info-box">
        <h2>Feedbacker</h2>
        <h3>
            Качество образования - в ваших руках!<br>
        </h3>
        {% if not user.is_authenticated %}
        <form id="login_form" class="login_form lock" role="form" method="post" action="{% url 'main:login' %}">
            {% csrf_token %}
            <div id="login_group" class="form-group">
                <label class="sr-only" for="username">Имя пользователя</label>
                <input type="text" class="input-lg form-control" name="username" id="username_login" placeholder="Имя пользователя" value="" maxlength="30">
            </div>
            <div id="password_group" class="form-group">
                <label class="sr-only" for="password">Пароль</label>
                <input type="password" class="input-lg form-control" name="password" id="password_login" placeholder="Пароль" value="" maxlength="50">
            </div>
            <button id="btn_login" name="login" class="btn_login input-lg btn btn-primary" type="submit" title="Вход в аккаунт">Войдите</button>
        </form>
        <h5>или <a href="{% url 'main:register' %}" title="Перейти к форме регистрации">Зарегистрируйтесь</a></h5>
        {% else %}
        {% if user.profile_type.short_name == "СТ" %}
        Твой голос важен. 
        {% endif %}
        {% if user.profile_type.short_name == "ПР" or user.profile_type.short_name == "ЗК" %}
        Вы можете стать лучше, и ваши студенты знают, как!
        {% endif %}
        <!-- Иди голосуй -->
        {% endif %}
    </section>
</div>

<div id="more-info-box" class="more-info-box">
    <div id="block_services" class="block_services">
        <div class="col-lg-4 col-md-4 col-sm-4">
            <section class="info-block">
                <h3 class="title">Студенту</h3>
                <p><ul class="list-unstyled">
                    <li>Высказать свое мнение о курсе</li>
                    <li>Сообщить о проблеме</li>
                    <li>Пройти тест</li>
                </ul></p>
                 <!--<a href="#">Узнать больше</a>-->
            </section>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <section class="info-block">
                <h3 class="title">Преподавателю</h3>
                <p><ul class="list-unstyled">
                    <li>Узнать свой рейтинг</li>
                    <li>Найти свои сильные и слабые стороны</li>
                    <li>Провести тестирование</li>
                </ul></p>
                 <!--<a href="#">Узнать больше</a>-->
            </section>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <section class="info-block">
                <h3 class="title">Руководителю</h3>
                <p><ul class="list-unstyled">
                    <li>Выявить лучших преподавателей</li>
                    <li>Понять слабые места системы</li>
                    <li>Получить наглядную статистику</li>
                </ul></p>
                <!--<a href="#">Узнать больше</a>-->
            </section>
        </div>
    </div>
    <div id="block_news" class="block_news">
        <div id="news_carousel" class="news_carousel carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#news_carousel" data-slide-to="0" class="active"></li>
                {% for newsbit in news %}
                <li data-target="#news_carousel" data-slide-to="{{ forloop.counter }}"></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <section class="news_item">
                        <p>{{ main.title }}</p>
                        <a class="ni_full_link" href="{{ main.get_absolute_url }}" hidden></a>
                    </section>
                </div>
                {% for newsbit in news %}
                <div class="item">
                    <section class="news_item">
                        <p>{{ newsbit.title }}</p>
                        <a class="ni_full_link" href="{{ newsbit.get_absolute_url }}" hidden></a>
                    </section>
                </div>
                {% endfor %}
            </div>
            <a class="left carousel-control" href="#news_carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#news_carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Войти{% endblock %}

{% block scripts %}
<script>$('#login_li').addClass('active');</script>
{% endblock %}

{% block content %}
<div class="row">
    {% if not user.is_authenticated %}
    <div class="col-lg-4 col-sm-3 col-xs-0"></div>
    <div class="col-lg-4 col-sm-6 col-xs-12">
        <div class="well well-sm login_form hcenter">
            <div id="login_form_div">
                <form class="lock" role="form" id="login_form" method="post" action="{% url 'main:login' %}">
                    <label for="login_form"><h2>Войдите:</h2></label>
                    <!--
                    <p>Для входа в демо-аккаунт преподавателя:<br/>
                    логин: demo, пароль: demo</p>
                    -->
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="sr-only" for="username">Имя пользователя:</label>
                        <input type="text" class="form-control" name="username" id="username_login" placeholder="Username" value="" maxlength="30">
                        <div class="errors_field">
                            {% if login_err %}
                                {{ login_err.0 }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="password">Password:</label>
                        <input type="password" class="form-control" name="password" id="password_login" placeholder="Пароль" value="" maxlength="50">
                        <div class="errors_field"></div>
                    </div>
                    <div id="result_field"></div>
                   
                    <div class="btn-group btn-group-justified">
                        <div class="btn-group"><button type="submit" name="submit" class="btn btn-primary" title="Вход в аккаунт">Вход</button></div>
                        <div class="btn-group"><div class="text-center"><a href="/user/password/reset/">Забыли пароль?</a></div></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-3 col-xs-0"></div>
    {% else %}
    <div class="col-lg-3 col-sm-2 col-xs-0"></div>
    <div class="col-lg-6 col-sm-8 col-xs-12">
        <div class="panel panel-info">
            <div class="panel-heading"><h4>Вы уже вошли в систему. Нет необходимости делать это ещё раз.</h4></div>
            <div class="panel-body">
                <p>Вы можете <a href="{% url 'main:my' %}">перейти в личный кабинет </a> или же <a href="{% url 'main:logout' %}">выйти из аккаунта</a>.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-2 col-xs-0"></div>
    {% endif %}
</div>
{% endblock %}

app/templates/app/student_rating_tab.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Student Rating{% endblock %}
 
{% block scripts %}
<script>
var student_rating_url = "{% url 'main:student_rating' %}";
</script>
<script type="text/javascript" src='{% static "app/scripts/ajax_core.js" %}'></script>
<script type="text/javascript" src='{% static "app/scripts/pages/student_rating.js" %}'></script>
{% endblock %}

{% block content %}
<div class="col-lg-2 col-sm-2 col-xs-0"></div>
<div class="col-lg-8 col-sm-8 col-xs-12">
    <div class="panel panel-info survey_panel">
        <div class="panel-heading">Student Rating</div>
    	<div class="panel-body">
			<div id="student_rating_panel_content">
			<!--
				<h2>Прием заявок закрыт. </h2>
				<h4>Редактирование также недоступно, поэтому если исправление действительно необходимо, <a style="color:#3366BB;" target = "_blank" href="/contact_admin/">обратитесь к администратору сайта.</a></h4>
				-->
				{% if edit %}             
				<div class="btn-group"><button type="submit" class="btn btn-primary" title="Отправка данных" onclick="fill_in_form();">Заполнить заявку на конкурс</button></div>
				{% endif %}
				<br />
				<br />
				<div> 
					<p id ="tabletitle" style="text-align: center;background-color:gray;color:white;padding-top:10px;padding-bottom:10px">Матрица компетенций студентов (нажмите, чтобы скрыть/открыть) </p> 
				</div>
				<div id="student_rating_loadable_content">
					<div class="table-responsive">
					<!--
						<table class="scoreboard-map">
							<tr>
								<td class="scm1">Президентская (места 1 - 3)</td>
								<td class="scm2">Верховной рады (места 4 - 5)</td>
								<td class="scm3">Масельського (место 6)</td>
								<td class="scm4">Янгеля (места 7 - 10)</td>
								<td class="scm5">Іванченко (места 11 - 14)</td>
							</tr>
							<tr>
								<td class="scm6">Новікова (места 15 - 20)</td>
								<td class="scm7">Свиридова (места 21 - 25)</td>
								<td class="scm8">Бондаренко (места 26 - 27)</td>
								<td class="scm9">Шакало (места 28 - 29)</td>
							</tr>
						</table>
						-->
						* Наведите на название колонки, чтобы увидеть его полностью
						<table class="table scoreboard" style="font-size: 12px;">
							<thead>
								<tr>
									<th>№</th>
									<th title="Фамилия Имя Отчество">ФИО</th>
									<th title="Факультет">Фак.</th>        
									<th title="Кафедра">Каф.</th>
									<th title="Группа">Гр.</th>
									<th title="Средний балл">Ср.</th>
									<!--<th title="Иностранные языки (сертификаты)">Ин. яз</th>-->
									<th title="Программные продукты; устройства и макеты, патенты на изобретения и полезные модели">Дост.</th>
									<th title="Призеры конкурсов, олимпиад и выставок, подтвержденные дипломами">Пр.</th>
									<th title="Журнальные статьи зарубежные">Ст. инт.</th>
									<th title="Журнальные статьи национальные">Ст. нац.</th>
									<th title="Доклады на конференциях и семинарах зарубежные">Док. зар.</th>
									<th title="Доклады на конференциях и семинарах национальные">Док. нац.</th>
									<th title="Спортивные и культурные мероприятия">Мер.</th>
									<th title="Наукометрия в Scopus, WoS (20k),  k – количество публикаций.">Scop.</th>
									<th title="Интегральная оценка">&Sigma;</th>
									<th title="Кем добавлено">Доб.</th>
									
										<th title="Редактировать"><span class="glyphicon glyphicon-pencil"></span></th>
										<th title="Удалить"><span class="glyphicon glyphicon-remove"></span></th>
									
								</tr>
							</thead>
							<thead>
								<tr>
									<th></th>
									<th></th>
									<th></th>        
									<th></th>
									<th></th>
									<th>x1</th>
									<!--<th>x50</th>-->
									<th>x20</th>
									<th>x10</th>
									<th>x20</th>
									<th>x10</th>
									<th>x15</th>
									<th>x5</th>
									<th>x5</th>
									<th>x20</th>
									<th>&Sigma;</th>
									<th></th>
									<!--
									<th></th>
									<th></th>
									-->
								</tr>
							</thead>
							<tbody>
								{% for el in students_data %}
								<tr>
									<td> {{ forloop.counter }} </td>
									<td title="ФИО студента">{{ el.last_name }}, {{ el.first_name }} {{ el.middle_name }}</td>
									<td title="Факультет">{{ el.faculty_txt }} </td>        
									<td title="Кафедра">{{ el.department_txt }}</td>
									<td title="Группа">{{ el.group_txt }}</td>
									<td title="Средний балл">{{ el.gpa }}</td>
									<!--<td title="Иностранные языки (сертификаты)">{{ el.english }}</td>-->
									<td title="Программные продукты; устройства и макеты, патенты на изобретения и полезные модели">{{ el.patents}}</td>
									<td title="Призеры конкурсов, олимпиад и выставок, подтвержденные дипломами">{{ el.competitions}}</td>
									<td title="Журнальные статьи зарубежные">{{ el.articles_int }}</td>
									<td title="Журнальные статьи национальные">{{ el.articles_nat }}</td>
									<td title="Доклады на конференциях и семинарах зарубежные">{{ el.presentation_int}}</td>
									<td title="Доклады на конференциях и семинарах национальные">{{ el.presentation_nat}}</td>
									<td title="Спортивные и культурные мероприятия">{{ el.sport }}</td>
									<td title="Наукометрия в Scopus, WoS (20k),  k – количество публикаций">{{ el.scopus }}</td>
									<td title="Интегральная оценка">{{ el.integral }}</td>
									<td title="Кем добавлено">{{ el.added_by }}</td>
									
									<td title="Редактировать">
										{% if el.added_by == user.inst_profile %}
										<a class="edit_link" href="{% url 'main:edit_student_rating' el.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
										{% else %}
										<span class="glyphicon glyphicon-pencil" style="color:lightgray;"></span>
										{% endif %}
									</td>
									<td title="Удалить">
										{% if el.added_by == user.inst_profile %}
										<a class="edit_link" href="{% url 'main:delete_student_rating' el.id %}"><span class="glyphicon glyphicon-remove" style="color:#B80000;"></span></a>
										{% else %}
										<span class="glyphicon glyphicon-remove" style="color:lightgray;"></span>
										{% endif %}
									</td>
									
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			
				
				<div> 
					<p id="application" style="text-align: center;background-color:gray;color:white;padding-top:10px;padding-bottom:10px">Заявление на участие в конкурсе (нажмите, чтобы скрыть/открыть)</p>
				</div>
				
				{% if not edit %}
				<form role="form" action="{% url 'main:student_rating' %}" method="post" id="student_rating_form">
				{% else %}
				<form role="form" action="{% url 'main:edit_student_rating' elid %}" method="post" id="student_rating_form">
				{% endif %}
					{% csrf_token %}
					{{ grant_form }}
					<br />
					<div class="btn-group" id="sbutton_wrapper">
						<button type="submit" class="btn btn-primary" id="submit" title="Отправка данных">Сохранить</button>                  
					</div>
				</form>
				
 <!--
				{% if edit %}             
				<form role="form" action="{% url 'main:edit_student_rating' elid %}" method="post" id="student_rating_form">
					{% csrf_token %}
					{{ grant_form }}
					<br />
					<div class="btn-group" id="sbutton_wrapper">
						<button type="submit" class="btn btn-primary" id="submit" title="Отправка данных">Сохранить</button>                  
					</div>
				</form>
				{% endif %}
				-->
			</div>
        </div>
    </div>
</div>
<div class="col-lg-2 col-sm-2 col-xs-0"></div>
{% endblock %}

<!--
	#Журнлаьные статье национальные (10k);
	articles_nat = models.PositiveSmallIntegerField()
	# Доклады на конференциях и семинарах зарубежные (15k); 
	presentation_int = models.PositiveSmallIntegerField()
	#национальные (5k);
	presentation_nat = models.PositiveSmallIntegerField()
	# Спортивные и культурные мероприятия (5k)
	sport = models.PositiveSmallIntegerField()
	# Наукометрия в Scopus, WoS (20k),  k – количество публикаций.
	scopus = models.PositiveSmallIntegerField()
	# Интегральная оценка
-->