DjangoWebProject/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from app.models import CustomUser, GTSIL_Results_Distribution
from rest_framework import routers, serializers, viewsets
from django.utils.translation import ugettext_lazy as _
import django_filters
from rest_framework import filters
from rest_framework import generics


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = CustomUser
        fields = ('url', 'username', 'is_staff', 'status_confirmed')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

"""
class UserSerializer(serializers.Serializer):
    email = serializers.EmailField()
    username = serializers.CharField(max_length=100)

class CommentSerializer(serializers.Serializer):
    user = UserSerializer()
    content = serializers.CharField(max_length=200)
    created = serializers.DateTimeField()
"""

class GroupSerializer(serializers.Serializer):
    name = serializers.CharField(max_length = 100)

class LectureSerializer(serializers.Serializer):
    lecture_start_time = serializers.DateTimeField()

class SubjectSerializer(serializers.Serializer):
    full_name = serializers.CharField(max_length = 100)
    subject_id = serializers.CharField(max_length=10)
class InstructorSerializer(serializers.Serializer):
    cist_id = serializers.CharField(max_length=5)
    last_name = serializers.CharField(max_length = 50)
    first_name = serializers.CharField(max_length = 50)
    middle_name = serializers.CharField(max_length = 50)
class CriteriaSerializer(serializers.Serializer):
    criteria_name = serializers.CharField(max_length=100)

class GTSILResultDistributionSerializer(serializers.HyperlinkedModelSerializer):
    lecture = LectureSerializer()
    group = GroupSerializer()
    subject = SubjectSerializer()
    instructor = InstructorSerializer()
    criteria = CriteriaSerializer()

    class Meta:
        model = GTSIL_Results_Distribution

class GTSILResultDistributionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = GTSIL_Results_Distribution.objects.all()
    serializer_class = GTSILResultDistributionSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('instructor', 'criteria','group', 'subject', 'lecture__gtsi__activity_type')
"""
class GTSILResultDistributionQueryViewSet(viewsets.ModelViewSet):
    queryset = GTSIL_Results_Distribution.objects.all()
    serializer_class = GTSILResultDistributionSerializer
    def get_querysety(self):
"""

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
#router.register(r'users', UserViewSet)
router.register(r'distributions', GTSILResultDistributionViewSet)
#router.register(r'distributions/subject=(?P<subject_id>.+)/(?P<instructor_id>.+)/(?P<activity_id>.+)$', GTSILResultDistributionQueryViewSet)

# Uncomment the next lines to enable the admin:
admin.autodiscover()

urlpatterns = [
    url(r'^', include('app.urls', namespace="main")),
    url(r'^', include('news.urls', namespace="news")),
    url(r'^',include('blog.urls', namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^apiz/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

app/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from django.views.generic import TemplateView
from app.views import (Index, Register, UserLogin, 
    RegisterStudent, RegisterInstructor, 
    AboutFeedbacker, AboutUs, 
    My, UserLogout, RegisterConfirm,
    ConfirmStatus, AttachGroup,
    EvaluateLecture, EvaluateSubject,
    FindProfile, AttachProfile,
    LectureResults, LectureResultsGraphData, SubjectResults,
    SubjectResultsGraphData, GroupsAndCriteria, Faq, ContactAdmin,
    TakeSurvey, ShowGroupInfo, MyProfile, Tutorials, TestResults,
    RefreshSchedule, StudentRatingView, OpenStudentRating, EditStudentRating,
    DeleteStudentRating, ShowComplaints)
from app.api import GTSILFeedback, Subjects
from app.views import email_exists, username_exists
from django.utils.translation import ugettext_lazy as _
from rest_framework import routers
from app import api
# Uncomment the next lines to enable the admin:
admin.autodiscover()
router = routers.DefaultRouter()
router.register(r'users', api.UserViewSet)
router.register(r'groups', api.GroupViewSet)

urlpatterns = patterns('',
    # Examples:
    url(r'^$', Index.as_view(), name = 'index'),    
    url(r'^login/$', UserLogin.as_view(), name = 'login'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls'), name = 'admin_doc'),

    # Uncomment the next line to enable the admin:
    url(r'^register/$', Register.as_view(), name = 'register'),
    url(r'^register/', include(patterns('',
        url(r'^student/$', RegisterStudent.as_view(), name = 'register_student'),
        url(r'^instructor/$', RegisterInstructor.as_view(), name = 'register_instructor'),
    ))),
    # url(r'^register_student/$', RegisterStudent.as_view(), name = 'register_student'),
    # url(r'^register_instructor/$', RegisterInstructor.as_view(), name = 'register_instructor'),
    url(r'^confirm_status/$', ConfirmStatus.as_view(), name = 'confirm_status'),
    url(r'^attach_group/$', AttachGroup.as_view(), name = 'attach_group'),
    url(_(r'^my/$'), My.as_view(), name = 'my'),
    url(r'^logout/$', UserLogout.as_view(), name = 'logout'),
    url(r'^about_us/$', AboutUs.as_view(), name = 'about_us'),
    url(r'^contact_admin/', ContactAdmin.as_view(), name = 'contact_admin'),
    url(r'^faq/$', Faq.as_view(), name='faq'),
    url(r'^about_feedbacker/$', AboutFeedbacker.as_view(), name = 'about_feedbacker'),            
    url(r'^admin/', include(admin.site.urls), name = 'admin'),
    url(r'^confirm/(?P<activation_key>\w+)/', RegisterConfirm.as_view(), name = 'confirm'),
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'registration/password_reset_form.html', 'post_reset_redirect' : '/user/password/reset/done/'}, name="password_reset"),
    (r'^user/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm', 
        {'post_reset_redirect' : '/user/password/done/'}),
    (r'^user/password/done/$',
        'django.contrib.auth.views.password_reset_complete'),
    url(r'^subjects/(?P<gtsi_id>\d+)/$', EvaluateSubject.as_view(), name='subject'),
    url(r'^subjects/(?P<gtsi_id>\d+)/vote/$', EvaluateSubject.as_view(), name='vote_subject'),
    url(r'^lectures/(?P<gtsil_id>\d+)/$', EvaluateLecture.as_view(), name='lecture'),
    url(r'^lectures/vote/(?P<gtsil_id>\d+)/$', EvaluateLecture.as_view(), name='vote_lecture'),
    url(r'^username_exists/(?P<username>([A-Z]|[a-z]|[0-9]|\.|_|\-){3,30})$', username_exists),
    url(r'^email_exists/(?P<email>([A-Z]|[a-z]|[0-9]|\@|\.|_|\-){3,30})$', email_exists),
    url(r'^find_profile/$', FindProfile.as_view(), name = 'find_profile'),
    url(r'^attach_profile/(?P<instructor_id>\d+)/$', AttachProfile.as_view(), name = 'attach_profile'),
    url(r'^results/(?P<gtsil_id>\d+)/$', LectureResults.as_view(), name='lecture_results'),
    url(r'^subject_results/(?P<subject_id>\d+)/$', SubjectResults.as_view(), name='subject_results'),
    url(r'^graphdata/$', LectureResultsGraphData.as_view(), name='graphdata'),
    url(r'^subjgraphdata/$', SubjectResultsGraphData.as_view(), name = 'subjgraphdata'),
    url(r'^getgroupscrit/$', GroupsAndCriteria.as_view(), name='getgroupscrit'),
    url(r'^api/v1/lectures/(?P<gtsil_id>\d+)/$', GTSILFeedback.as_view(), name='gtsil_feedback_api'),
    url(r'^api/v1/subjects/$', Subjects.as_view(), name='subjects_api'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^surveys/(?P<survey_id>\w+-\w+-\w+-\w+-\w+)/$', TakeSurvey.as_view(), name = 'survey'),
    url(r'^group/(?P<group_id>\w+)/$', ShowGroupInfo.as_view(), name = 'group_info'),
    url(r'^my/profile/$', MyProfile.as_view(), name = 'my_profile'),
    url(r'^tutorials/$', Tutorials.as_view(), name = 'tutorials'),
    url(r'^survey_results/(?P<survey_id>\w+-\w+-\w+-\w+-\w+)/(?P<group_id>\d+)/$', TestResults.as_view(), name = 'survey_results'),
    url(r'^refresh_schedule/$', RefreshSchedule.as_view(), name = 'refresh_schedule'),
    url(r'^student_rating/$', StudentRatingView.as_view(), name='student_rating'),
    url(r'^open_student_rating/$', OpenStudentRating.as_view(), name='open_student_rating'),
    url(r'^edit_student_rating/(?P<rating_id>\d+)/$', EditStudentRating.as_view(), name='edit_student_rating'),
    url(r'^delete_student_rating/(?P<rating_id>\d+)/$', DeleteStudentRating.as_view(), name='delete_student_rating'),
    url(r'^show_complaints/$', ShowComplaints.as_view(), name='show_complaints'),
    # url(r'^confirm_status_page/$', ConfirmStatusPage.as_view(), name="confirm_status_page"),
)

blog/urls.py
"""
Definition of urls for DjangoWebProject.
"""


from datetime import datetime
from django.conf.urls import patterns, url,include
from django.contrib import admin
from django.views.generic import TemplateView
from blog.views import (Blog, CreateBlogView, BlogPostView, UpdateBlogPostView,
    DeleteBlogPostView, UpdateCommentView, DeleteCommentView)
from django.utils.translation import ugettext_lazy as _

# Uncomment the next lines to enable the admin:
admin.autodiscover()


urlpatterns = patterns('',
	url(r'^blog/$', Blog.as_view(), name='blog',),
    url(r'^new$', CreateBlogView.as_view(), name='blog-new',),
    url(r'^(?P<pk>\d+)/$', BlogPostView.as_view(), name='blogpost-view',),
    url(r'^edit/(?P<pk>\d+)/$', UpdateBlogPostView.as_view(), name='blogpost-edit',),
    url(r'^(?P<blogpost_id>\d+)/edit_comment/(?P<pk>\d+)/$', UpdateCommentView.as_view(), name='comment-edit',),
    url(r'^delete/(?P<pk>\d+)/$', DeleteBlogPostView.as_view(), name='blogpost-delete',),
    url(r'^(?P<blogpost_id>\d+)/delete-comment/(?P<pk>\d+)/$', DeleteCommentView.as_view(), name='comment-delete',),)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link type="image/png" rel="shortcut icon" type="image/png" href="{% static 'app\images\icon\favicon.png' %}"/>
        <link type="image/png" rel="icon" href="{% static 'app\images\icon\touch-icon-120.png' %}">
        <link type="image/png" rel="apple-touch-icon" sizes="76x76" href="{% static 'app\images\icon\touch-icon-76.png' %}">
        <link type="image/png" rel="apple-touch-icon" sizes="120x120" href="{% static 'app\images\icon\touch-icon-120.png' %}">
        <link type="image/png" rel="apple-touch-icon" sizes="152x152" href="{% static 'app\images\icon\touch-icon-152.png' %}">
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->
        <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'app/css/base.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <header id="page_header" class="page_header">
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container-fluid">
                    <div id="navbar_header" class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar_main">
                            <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'main:index' %}">Feedbacker</a>
                    </div>
                    <div id="navbar_main" class="collapse navbar-collapse">
                        <ul id="navbar_main_left" class="nav navbar-nav">
                            {% if user.is_authenticated %}
                            <li id="my_li"><a href="{% url 'main:my' %}">Мой кабинет</a></li>
                            {% endif %}
                            <li id="open_student_rating_li"><a href="{% url 'main:open_student_rating' %}">Именные стипендии</a></li>
                            <li id="help_li" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Помощь
                                <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li id="tutorials_li"><a href="{% url 'main:tutorials' %}">Туториалы</a></li>
                                    <li id="faq_li"><a href="{% url 'main:faq' %}">FAQ</a></li>
                                    <li id="contact_admin_li"><a href="{% url 'main:contact_admin' %}">Написать администратору</a></li>
                                </ul>
                            </li>
                            <li id="about_us_li" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">О Нас
                                <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li id="about_team_li"><a href="{% url 'main:about_us' %}">О команде</a></li>
                                    <li id="contacts_li"><a href="{% url 'main:contact_admin' %}">Контакты</a></li>
                                    <li id="dev_blog_li"><a href="{% url 'blog:blog' %}">Блог разработчиков</a></li>
                                </ul>
                            </li>
                            {% block navbar %}{% endblock %}
                        </ul>
                        <ul id="navbar_main_right" class="nav navbar-nav navbar-right">
                            {% block navbar_right %}{% endblock %}
                            {% if not user.is_authenticated %}
                            <li id="register_li"><a href="{% url 'main:register' %}"><span class="navbar-glyphicon glyphicon glyphicon-check"></span>Регистрация</a></li>
                            <li id="login_li"><a href="{% url 'main:login' %}"><span class="navbar-glyphicon glyphicon glyphicon-log-in"></span>Вход</a></li>
                            {% else %}
                            <li id="user_li" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user navbar-glyphicon"></span>{{user.first_name}}
                                <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li id="my_profile_li"><a href="{% url 'main:my_profile' %}">Мой профиль</a></li>
                                </ul>
                            </li>
                            <li id="logout_li"><a href="{% url 'main:logout' %}"><span class="navbar-glyphicon glyphicon glyphicon-log-out"></span>Выход</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div id="page_wrapper" class="page_wrapper container-fluid">
            <aside>
                <div class="alert alert-danger" hidden>
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong class="alert-title">Внимание!</strong>Вы используете <b><i>устаревший браузер</b></i>, что может скажеться на опыте использования сервиса. Рекомендуем вам использовать что-то поновее.
                </div>
                {% if show_db_warning %}
                <div class="alert alert-danger">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong class="alert-title">Внимание!</strong> В данный момент ведутся работы на сайте. В связи с этим некоторые данные могут быть потеряны, результаты голосования могут быть не сохранены, поэтому лучше зайдите попозже.
                </div>
                {% endif %}
                <noscript>
                    <div class="alert alert-danger">
                        <strong class="alert-title">Внимание!</strong>Для корректной работы необходимы <i><b>Cookies</b></i> и <i><b>JavaScript</b></i>!
                    </div>
                </noscript>
                <div id="cookies_div" hidden>
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong class="alert-title">Внимание!</strong>Для корректной работы необходимы <i><b>Cookies</b></i>!
                    </div>
                </div>
            </aside>
            <main class="page_content">
                {% block content %}{% endblock %}
            </main>
        </div>
        <footer id="page_footer" class="page_footer text-center">
            <span>Copyright 2015-2016, LogovoLogiki.</span>
            <a href="{% url 'main:about_us' %}">О Нас</a>
            <span>Made in NURE. Made in Ukraine.</span>
        </footer>
        <!--<script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>-->
        <!--<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>-->
        <script type="text/javascript" src='{% static "app/scripts/jquery.min.js" %}'></script>
        <script type="text/javascript" src='{% static "app/scripts/bootstrap.min.js" %}'></script>
        <script type="text/javascript" src='{% static "app/scripts/showhide_div.js" %}'></script>
        <script type="text/javascript" src='{% static "app/scripts/pages/base.js" %}'></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

app/templates/base_my.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-lg-2 col-lg-push-10 col-sm-3 col-sm-push-9">
        <div class="inform_block">
            {% block inform_block %}{% endblock %}
		</div>
    </div>
    <div class="col-lg-2 col-lg-pull-2 col-sm-3 col-sm-pull-3">
        <div class="sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
    <div class="col-lg-8 col-lg-pull-2 col-sm-6 col-sm-pull-3">
        <div class="row">
            <div class="main_block">
                {% block main_block %}{% endblock %}
            </div>
        </div>
        <div class="row">
            <div class="rate_block">
                {% block display_block %}{% endblock %}
            </div>
        </div>
    </div>
</div>
{% endblock %}